/**
 * ByteRover CLI generated rule template tag.
 */
export const BRV_RULE_TAG = 'Generated by ByteRover CLI for'

/**
 * Boundary markers for managed ByteRover rule sections.
 * Used to identify and replace ByteRover-generated content in shared instruction files.
 */
export const BRV_RULE_MARKERS = {
  END: '<!-- END BYTEROVER RULES -->',
  START: '<!-- BEGIN BYTEROVER RULES -->',
} as const

/**
 * Checks if the BRV markers section contains MCP tool references (brv-query/brv-curate).
 * Only checks within the markers section to avoid false positives from user content.
 */
export const hasMcpToolsInBrvSection = (content: string): boolean => {
  const startIdx = content.indexOf(BRV_RULE_MARKERS.START)
  const endIdx = content.indexOf(BRV_RULE_MARKERS.END)
  if (startIdx === -1 || endIdx === -1) return false
  // eslint-disable-next-line unicorn/prefer-set-has
  const brvSection = content.slice(startIdx, endIdx)
  return brvSection.includes('brv-query') || brvSection.includes('brv-curate')
}
