import {dump} from 'js-yaml'

/**
 * Answers collected from the onboarding wizard.
 */
export type WizardAnswers = {
  budget?: {globalMonthlyCents: number}
  /** Whether to enable enrichment edges between providers (default: true when 2+ providers) */
  enrichment?: boolean
  providers: {
    config: Record<string, unknown>
    enabled: boolean
    id: string
  }[]
}

/**
 * Result from scaffoldConfig — YAML string plus any warnings.
 */
export type ScaffoldResult = {
  /** Warnings about dropped duplicate entries (e.g. multiple obsidian vaults) */
  warnings: string[]
  /** YAML config string ready to write to `.brv/swarm/config.yaml` */
  yaml: string
}

/**
 * Providers whose config schema supports only a single instance.
 * Duplicates produce a warning and the last entry wins.
 */
const SINGLE_INSTANCE_PROVIDERS = new Set(['byterover', 'gbrain', 'hindsight', 'honcho', 'obsidian'])

/**
 * Map provider IDs to their YAML key names.
 */
const PROVIDER_YAML_KEYS: Record<string, string> = {
  'byterover': 'byterover',
  'gbrain': 'gbrain',
  'hindsight': 'hindsight',
  'honcho': 'honcho',
  'local-markdown': 'local_markdown',
  'obsidian': 'obsidian',
}

/**
 * Pure function: transforms wizard answers into a YAML config string.
 * No side effects — fully testable.
 *
 * When multiple entries share the same provider ID:
 * - `local-markdown`: folders arrays are merged (schema supports multiple folders)
 * - All others: last entry wins, earlier entries produce a warning
 *
 * @param answers - Wizard answers with provider selections and config
 * @returns ScaffoldResult with YAML string and any warnings
 */
export function scaffoldConfig(answers: WizardAnswers): ScaffoldResult {
  const config: Record<string, unknown> = {}
  const warnings: string[] = []

  // Build providers section, merging duplicate entries
  const providers: Record<string, Record<string, unknown>> = {}
  for (const provider of answers.providers) {
    if (!provider.enabled) continue

    const yamlKey = PROVIDER_YAML_KEYS[provider.id] ?? provider.id
    const existing = providers[yamlKey]

    if (existing && provider.config.folders && existing.folders) {
      // Merge folders arrays for local_markdown (multiple folder entries)
      existing.folders = [
        ...(existing.folders as unknown[]),
        ...(provider.config.folders as unknown[]),
      ]
    } else if (existing && SINGLE_INSTANCE_PROVIDERS.has(provider.id)) {
      // Single-instance provider: last entry wins, warn about earlier
      const droppedDetail = existing.vault_path ?? existing.repo_path ?? existing.connection_string ?? provider.id
      warnings.push(
        `Multiple ${provider.id} entries selected — config only supports one. ` +
        `Keeping the last selection; dropped earlier entry (${droppedDetail}).`
      )
      Object.assign(existing, provider.config)
    } else if (existing) {
      Object.assign(existing, provider.config)
    } else {
      providers[yamlKey] = {
        enabled: true,
        ...provider.config,
      }
    }
  }

  config.providers = providers

  // Build enrichment section when user opted in (or default true for 2+ providers)
  if (answers.enrichment !== false) {
    const enabledIds = new Set(answers.providers.filter((p) => p.enabled).map((p) => p.id))
    if (enabledIds.size >= 2 && enabledIds.has('byterover')) {
      // ByteRover is the master — it feeds context to all other providers
      const edges: Array<{from: string; to: string}> = []
      if (enabledIds.has('obsidian')) edges.push({from: 'byterover', to: 'obsidian'})
      if (enabledIds.has('local-markdown')) edges.push({from: 'byterover', to: 'local-markdown'})
      if (enabledIds.has('gbrain')) edges.push({from: 'byterover', to: 'gbrain'})
      if (edges.length > 0) {
        config.enrichment = {edges}
      }
    }
  }

  // Build budget section (only if specified)
  if (answers.budget) {
    config.budget = {
      // eslint-disable-next-line camelcase -- YAML budget key
      global_monthly_cap_cents: answers.budget.globalMonthlyCents,
    }
  }

  const header = '# Memory Swarm Configuration for ByteRover-CLI\n# Generated by `brv swarm onboard`\n\n'
  const body = dump(config, {
    indent: 2,
    lineWidth: 120,
    noRefs: true,
    sortKeys: false,
  })

  return {warnings, yaml: header + body}
}
